/**
 * Widget catalog — seeded once at startup.
 */
import { db, widgetDefinitionsTable } from "@workspace/db";
import { logger } from "./logger.js";

export const WIDGET_CATALOG = [
  {
    key: "kpi_cards",
    name: "KPI Cards",
    description: "Tarjetas de indicadores clave de rendimiento",
    category: "indicadores",
    configSchemaJson: { type: "object", properties: { metric: { type: "string" }, mode: { type: "string" } } },
    defaultConfigJson: { metric: "total", mode: "default" },
    supportsGlobalFilters: true,
    supportsDateRange: true,
    supportsDrilldown: false,
  },
  {
    key: "dynamic_table",
    name: "Tabla Dinámica",
    description: "Tabla con datos configurables y paginación",
    category: "datos",
    configSchemaJson: { type: "object", properties: { columns: { type: "array", items: { type: "string" } }, limit: { type: "number" } } },
    defaultConfigJson: { columns: [], limit: 20 },
    supportsGlobalFilters: true,
    supportsDateRange: true,
    supportsDrilldown: true,
  },
  {
    key: "alerts_list",
    name: "Lista de Alertas",
    description: "Lista de alertas activas del sistema",
    category: "alertas",
    configSchemaJson: { type: "object", properties: { daysAhead: { type: "number" } } },
    defaultConfigJson: { daysAhead: 7 },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "traffic_light",
    name: "Semáforo",
    description: "Indicador de estado con semáforo verde/amarillo/rojo",
    category: "indicadores",
    configSchemaJson: {},
    defaultConfigJson: {},
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "ranking",
    name: "Ranking",
    description: "Lista ordenada por relevancia o puntuación",
    category: "datos",
    configSchemaJson: { type: "object", properties: { limit: { type: "number" } } },
    defaultConfigJson: { limit: 5 },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "bar_chart",
    name: "Gráfico de Barras",
    description: "Gráfico de barras configurable",
    category: "gráficos",
    configSchemaJson: { type: "object", properties: { groupBy: { type: "string" }, chartType: { type: "string" } } },
    defaultConfigJson: { groupBy: "month", chartType: "bar" },
    supportsGlobalFilters: true,
    supportsDateRange: true,
    supportsDrilldown: false,
  },
  {
    key: "line_chart",
    name: "Gráfico de Líneas",
    description: "Gráfico de líneas configurable",
    category: "gráficos",
    configSchemaJson: { type: "object", properties: { groupBy: { type: "string" } } },
    defaultConfigJson: { groupBy: "month" },
    supportsGlobalFilters: true,
    supportsDateRange: true,
    supportsDrilldown: false,
  },
  {
    key: "smart_summary",
    name: "Resumen Inteligente",
    description: "Resumen automático de datos importantes",
    category: "inteligencia",
    configSchemaJson: {},
    defaultConfigJson: {},
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "calendar",
    name: "Calendario",
    description: "Vista de calendario con eventos y vencimientos",
    category: "tiempo",
    configSchemaJson: { type: "object", properties: { view: { type: "string", enum: ["month", "week"] } } },
    defaultConfigJson: { view: "month" },
    supportsGlobalFilters: false,
    supportsDateRange: true,
    supportsDrilldown: false,
  },
  {
    key: "news_feed",
    name: "Feed de Noticias",
    description: "Últimas noticias económicas y fiscales",
    category: "información",
    configSchemaJson: { type: "object", properties: { limit: { type: "number" } } },
    defaultConfigJson: { limit: 8 },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "quotes",
    name: "Cotizaciones",
    description: "Cotizaciones del dólar y monedas",
    category: "economía",
    configSchemaJson: {},
    defaultConfigJson: {},
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "pending_tasks",
    name: "Tareas Pendientes",
    description: "Listado de tareas abiertas del usuario",
    category: "productividad",
    configSchemaJson: { type: "object", properties: { limit: { type: "number" } } },
    defaultConfigJson: { limit: 8 },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "upcoming_due_dates",
    name: "Próximos Vencimientos",
    description: "Vencimientos fiscales próximos",
    category: "fiscal",
    configSchemaJson: { type: "object", properties: { limit: { type: "number" }, daysAhead: { type: "number" } } },
    defaultConfigJson: { limit: 10, daysAhead: 30 },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "expense_categories",
    name: "Categorías de Gastos",
    description: "Distribución de gastos por categoría",
    category: "finanzas",
    configSchemaJson: { type: "object", properties: { groupBy: { type: "string" } } },
    defaultConfigJson: { groupBy: "category" },
    supportsGlobalFilters: true,
    supportsDateRange: true,
    supportsDrilldown: false,
  },
  {
    key: "recent_transactions",
    name: "Movimientos Recientes",
    description: "Últimos movimientos financieros",
    category: "finanzas",
    configSchemaJson: { type: "object", properties: { limit: { type: "number" } } },
    defaultConfigJson: { limit: 8 },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "goals_progress",
    name: "Progreso de Objetivos",
    description: "Progreso hacia objetivos financieros personales",
    category: "finanzas",
    configSchemaJson: {},
    defaultConfigJson: {},
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "checklist",
    name: "Checklist",
    description: "Lista de verificación configurable",
    category: "productividad",
    configSchemaJson: { type: "object", properties: { items: { type: "array" } } },
    defaultConfigJson: { items: [] },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "recent_activity",
    name: "Actividad Reciente",
    description: "Registro de actividad del sistema",
    category: "sistema",
    configSchemaJson: { type: "object", properties: { limit: { type: "number" } } },
    defaultConfigJson: { limit: 10 },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "quick_links",
    name: "Accesos Rápidos",
    description: "Lista de links y accesos directos configurables",
    category: "navegación",
    configSchemaJson: { type: "object", properties: { links: { type: "array" } } },
    defaultConfigJson: { links: [] },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
  {
    key: "text_block",
    name: "Bloque de Texto",
    description: "Bloque de texto libre o HTML configurable",
    category: "contenido",
    configSchemaJson: { type: "object", properties: { content: { type: "string" }, format: { type: "string" } } },
    defaultConfigJson: { content: "", format: "text" },
    supportsGlobalFilters: false,
    supportsDateRange: false,
    supportsDrilldown: false,
  },
];

export async function seedWidgetCatalog(): Promise<void> {
  try {
    const existing = await db.select({ key: widgetDefinitionsTable.key }).from(widgetDefinitionsTable);
    const existingKeys = new Set(existing.map(w => w.key));
    const toInsert = WIDGET_CATALOG.filter(w => !existingKeys.has(w.key));
    if (toInsert.length > 0) {
      await db.insert(widgetDefinitionsTable).values(toInsert);
      logger.info({ count: toInsert.length }, "Studio: widget catalog seeded");
    }
  } catch (err) {
    logger.error({ err }, "Studio: widget catalog seed error");
  }
}
